- name: play level variables
  hosts: local
  connection: local 
  vars:
    nme: "vikas"
    designation: "DevOps Engineer"
  tasks: 
  - name: printing the info
    vars:
       nme: "navish"
    ansible.builtin.debug:
      msg: "Info : {{nme}}, {{designation}}"