- name: conditions
  hosts: local
  connection: local
  vars:
    number: 5
  tasks:
  - name: check the number is less 10 or not
    ansible.builtin.debug:
       msg: "Give number {{number}} is less than 10"
    when: number < 10